/**
 * Agent Datasets Page
 *
 * Dedicated page listing datasets generated by (or auto-detected in chat
 * with) the student's submitted agent. Layout mirrors the Test & Reflect
 * page: breadcrumb + agent header card with a Back button + the existing
 * AgentDatasetTab body.
 *
 * Access is gated to submitted agents via canTestAgent — drafts are
 * redirected back to the builder with a toast.
 */

import { useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowLeft, Bot } from 'lucide-react';
import toast from 'react-hot-toast';
import { agentAssignmentsApi } from '../../api/agentAssignments';
import { resolveFileUrl } from '../../api/client';
import { Button } from '../../components/common/Button';
import { Loading } from '../../components/common/Loading';
import { Breadcrumb } from '../../components/common/Breadcrumb';
import { AgentDatasetTab } from '../../components/agent-assignment/AgentDatasetTab';
import { canTestAgent } from '../../utils/agentAccess';
import activityLogger from '../../services/activityLogger';

export const AgentDatasets = () => {
  const { t } = useTranslation(['teaching', 'common', 'navigation']);
  const { courseId, assignmentId } = useParams<{
    courseId: string;
    assignmentId: string;
  }>();
  const navigate = useNavigate();
  const assId = parseInt(assignmentId!, 10);

  const { data, isLoading, error } = useQuery({
    queryKey: ['myAgentConfig', assId],
    queryFn: () => agentAssignmentsApi.getMyAgentConfig(assId),
  });

  const builderPath = `/courses/${courseId}/agent-assignments/${assignmentId}`;
  const testPath = `${builderPath}/test`;
  const parsedCourseId = courseId ? parseInt(courseId, 10) : undefined;

  // Log page view
  useEffect(() => {
    if (data?.config && canTestAgent(data.config)) {
      activityLogger.logAgentDatasetsViewed(data.config.id, parsedCourseId);
    }
  }, [data?.config?.id, parsedCourseId]);

  useEffect(() => {
    if (!isLoading && data && !canTestAgent(data.config)) {
      toast.error(t('submit_before_test'));
      navigate(builderPath, { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, data]);

  if (isLoading) {
    return <Loading fullScreen text={t('loading_your_agent')} />;
  }

  if (error || !data) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8 text-center">
        <Bot className="w-12 h-12 text-gray-400 mx-auto mb-4" />
        <h1 className="text-2xl font-bold text-gray-900 mb-2">
          {t('failed_to_load_assignment')}
        </h1>
        <Button onClick={() => navigate(builderPath)}>{t('common:back')}</Button>
      </div>
    );
  }

  const { assignment, config } = data;
  if (!canTestAgent(config)) return null;

  const courseName = assignment.course?.title || 'Course';

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 md:py-8">
      <div className="mb-6">
        <Breadcrumb
          items={[
            { label: t('navigation:courses'), href: '/courses' },
            { label: courseName, href: `/courses/${courseId}` },
            { label: t('assignments'), href: `/courses/${courseId}/assignments` },
            { label: assignment.title, href: builderPath },
            { label: t('datasets') },
          ]}
        />
      </div>

      {/* Agent header card with Back button */}
      <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4 mb-4">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 sm:gap-4">
          <div className="flex items-center gap-3 min-w-0">
            {config!.avatarImageUrl ? (
              <img
                src={resolveFileUrl(config!.avatarImageUrl)}
                alt={config!.agentName}
                className="w-10 h-10 rounded-full object-cover shadow-sm flex-shrink-0"
              />
            ) : (
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center shadow-sm flex-shrink-0">
                <Bot className="w-5 h-5 text-white" />
              </div>
            )}
            <div className="min-w-0">
              <h1 className="text-base font-bold text-gray-900 dark:text-gray-100 truncate">
                {config!.agentName}
              </h1>
              {config!.agentTitle && (
                <p className="text-sm text-violet-600 font-medium truncate">
                  {config!.agentTitle}
                </p>
              )}
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-1 truncate">
                {assignment.title}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <Button
              variant="secondary"
              size="sm"
              onClick={() => navigate(testPath)}
              icon={<ArrowLeft className="w-4 h-4" />}
            >
              {t('common:back')}
            </Button>
          </div>
        </div>
      </div>

      <AgentDatasetTab assignmentId={assId} config={config} />
    </div>
  );
};
