@echo off
setlocal enabledelayedexpansion

echo ==========================================
echo   LAILA LMS Setup Script (Windows)
echo ==========================================
echo.

:: Check for Node.js
where node >nul 2>nul
if %errorlevel% neq 0 (
    echo Error: Node.js is not installed. Please install Node.js 18+ first.
    exit /b 1
)

for /f "tokens=1,2,3 delims=." %%a in ('node -v') do (
    set NODE_MAJOR=%%a
)
set NODE_MAJOR=%NODE_MAJOR:~1%

echo Node.js detected
echo.

:: Setup server environment
echo Setting up server environment...
cd server

if not exist .env (
    echo Creating server\.env file...

    :: Generate secrets using Node.js
    for /f %%i in ('node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"') do set JWT_SECRET=%%i
    for /f %%i in ('node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"') do set SESSION_SECRET=%%i

    (
        echo # Auto-generated by setup script
        echo DATABASE_URL="file:./dev.db"
        echo JWT_SECRET=!JWT_SECRET!
        echo SESSION_SECRET=!SESSION_SECRET!
        echo PORT=5001
        echo NODE_ENV=development
        echo CLIENT_URL=*
        echo.
        echo # AI Providers - Add your API keys here
        echo # OPENAI_API_KEY=your-openai-api-key
        echo # OPENAI_MODEL=gpt-4o-mini
        echo # GEMINI_API_KEY=your-gemini-api-key
        echo # GEMINI_MODEL=gemini-pro
    ) > .env

    echo Created server\.env with auto-generated secrets
) else (
    echo server\.env already exists
)

cd ..

:: Setup client environment
echo.
echo Setting up client environment...
cd client

if not exist .env (
    (
        echo # Auto-generated by setup script
        echo # These are optional - defaults work for local development
        echo # VITE_PORT=5174
        echo # VITE_API_TARGET=http://localhost:5001
    ) > .env
    echo Created client\.env
) else (
    echo client\.env already exists
)

cd ..

:: Install dependencies
echo.
echo Installing dependencies...
call npm run install:all

:: Setup database
echo.
echo Setting up database...
cd server
call npx prisma generate
call npx prisma db push
echo Database schema applied

:: Seed database
echo.
echo Seeding database with default data...
call npx prisma db seed
echo Database seeded

cd ..

echo.
echo ==========================================
echo   Setup Complete!
echo ==========================================
echo.
echo Default login credentials:
echo.
echo   Admin:      admin@laila.edu / admin123
echo   Instructor: instructor@laila.edu / instructor123
echo   Student:    student@laila.edu / student123
echo.
echo To start the application:
echo   npm run dev
echo.
echo The app will be available at:
echo   Frontend: http://localhost:5174
echo   Backend:  http://localhost:5001
echo.

endlocal
