#!/bin/bash

# LAILA LMS Setup Script
# This script sets up a fresh installation on any computer

set -e

echo "=========================================="
echo "  LAILA LMS Setup Script"
echo "=========================================="
echo ""

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "Error: Node.js is not installed. Please install Node.js 18+ first."
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo "Error: Node.js 18+ is required. Current version: $(node -v)"
    exit 1
fi

echo "✓ Node.js $(node -v) detected"
echo ""

# Generate secrets
generate_secret() {
    if command -v openssl &> /dev/null; then
        openssl rand -base64 32
    else
        # Fallback for systems without openssl
        node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
    fi
}

# Setup server environment
echo "Setting up server environment..."
cd server

if [ ! -f .env ]; then
    echo "Creating server/.env file..."

    JWT_SECRET=$(generate_secret)
    SESSION_SECRET=$(generate_secret)

    cat > .env << EOF
# Auto-generated by setup script
DATABASE_URL="file:./dev.db"
JWT_SECRET=${JWT_SECRET}
SESSION_SECRET=${SESSION_SECRET}
PORT=5001
NODE_ENV=development
CLIENT_URL=*

# AI Providers - Add your API keys here
# OPENAI_API_KEY=your-openai-api-key
# OPENAI_MODEL=gpt-4o-mini
# GEMINI_API_KEY=your-gemini-api-key
# GEMINI_MODEL=gemini-pro
EOF
    echo "✓ Created server/.env with auto-generated secrets"
else
    echo "✓ server/.env already exists (keeping existing configuration)"
fi

cd ..

# Setup client environment (optional, defaults work fine)
echo ""
echo "Setting up client environment..."
cd client

if [ ! -f .env ]; then
    cat > .env << EOF
# Auto-generated by setup script
# These are optional - defaults work for local development
# VITE_PORT=5174
# VITE_API_TARGET=http://localhost:5001
EOF
    echo "✓ Created client/.env"
else
    echo "✓ client/.env already exists"
fi

cd ..

# Install dependencies
echo ""
echo "Installing dependencies..."
npm run install:all

# Setup database
echo ""
echo "Setting up database..."
cd server
npx prisma generate
npx prisma db push
echo "✓ Database schema applied"

# Seed database
echo ""
echo "Seeding database with default data..."
npx prisma db seed
echo "✓ Database seeded"

cd ..

echo ""
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "Default login credentials:"
echo ""
echo "  Admin:      admin@laila.edu / admin123"
echo "  Instructor: instructor@laila.edu / instructor123"
echo "  Student:    student@laila.edu / student123"
echo ""
echo "To start the application:"
echo "  npm run dev"
echo ""
echo "The app will be available at:"
echo "  Frontend: http://localhost:5174"
echo "  Backend:  http://localhost:5001"
echo ""
