-- =============================================================================
-- add_forum_thread_likes
--
-- Adds a join table that records "the user liked this discussion". Purely
-- additive — no existing columns or tables change. Safe to run in prod
-- with no data backfill.
--
-- (The autogenerated SQL also re-included the forum_collapse_layers DDL
-- because that prior migration isn't yet on git HEAD when `migrate diff`
-- runs; that block was stripped here so this migration applies cleanly
-- on top of forum_collapse_layers and contains only the likes table.)
-- =============================================================================

-- CreateTable
CREATE TABLE "forum_thread_likes" (
    "id"         SERIAL  NOT NULL,
    "thread_id"  INTEGER NOT NULL,
    "user_id"    INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "forum_thread_likes_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "forum_thread_likes_thread_id_idx" ON "forum_thread_likes"("thread_id");

-- CreateIndex
CREATE INDEX "forum_thread_likes_user_id_idx" ON "forum_thread_likes"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "forum_thread_likes_thread_id_user_id_key" ON "forum_thread_likes"("thread_id", "user_id");

-- AddForeignKey
ALTER TABLE "forum_thread_likes"
  ADD CONSTRAINT "forum_thread_likes_thread_id_fkey"
    FOREIGN KEY ("thread_id") REFERENCES "forum_threads"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "forum_thread_likes"
  ADD CONSTRAINT "forum_thread_likes_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
