import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { BUILD_INFO } from './buildInfo.js';

/**
 * Guardrails for the things a release has to be able to state about itself:
 * its version, its licence, and what open-source software it is built on.
 *
 * All three went wrong at once on a real deployment — it served no About page,
 * no licence notice, and reported a version that was a hardcoded fallback —
 * and nothing failed. These make each of those a test failure instead.
 */

function repoRoot(): string {
  let dir = process.cwd();
  for (;;) {
    if (existsSync(join(dir, 'deploy')) && existsSync(join(dir, 'server'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) throw new Error(`Repo root not found from ${process.cwd()}`);
    dir = parent;
  }
}

const ROOT = repoRoot();
const read = (p: string) => readFileSync(resolve(ROOT, p), 'utf8');
const readJson = (p: string) => JSON.parse(read(p));

interface Manifest {
  carmLicense: string;
  carmLicenseVersion: string;
  counts: { total: number; client: number; server: number };
  client: Array<{ name: string; version: string | null; license: string }>;
  server: Array<{ name: string; version: string | null; license: string }>;
}

describe('licence', () => {
  it('ships a LICENSE file at the repository root', () => {
    expect(existsSync(resolve(ROOT, 'LICENSE'))).toBe(true);
    expect(read('LICENSE').trim().length).toBeGreaterThan(500);
  });

  // The About page shows the licence version parsed from this heading rather
  // than a hardcoded string, so that a "v1.3" label can never sit beside v1.4
  // text. That only holds while the heading stays parseable.
  it('has a parseable version heading', () => {
    const heading = read('LICENSE').match(/^#\s*(.+)$/m)?.[1]?.trim();
    expect(heading, 'LICENSE must open with a `# <name> v<x.y>` heading').toBeDefined();
    expect(heading).toMatch(/v\d+\.\d+$/);
  });

  it('agrees with the generated attribution manifest', () => {
    const manifest: Manifest = readJson('client/src/data/third-party-licenses.json');
    const heading = read('LICENSE').match(/^#\s*(.+)$/m)?.[1]?.trim();
    expect(manifest.carmLicenseVersion).toBe(heading);
    // The full text is embedded so the page can render it offline.
    expect(manifest.carmLicense.trim()).toBe(read('LICENSE').trim());
  });
});

describe('third-party attribution manifest', () => {
  const manifest: Manifest = readJson('client/src/data/third-party-licenses.json');

  // The manifest is generated by the client prebuild but committed, so it
  // silently goes stale the moment a dependency is added or removed without a
  // build. It shipped listing two packages that had already been uninstalled.
  it.each([
    ['client', 'client/package.json'],
    ['server', 'server/package.json'],
  ] as const)('lists exactly the direct dependencies of %s', (workspace, pkgPath) => {
    const declared = Object.keys(readJson(pkgPath).dependencies ?? {}).sort();
    const recorded = manifest[workspace].map((d) => d.name).sort();

    const missing = declared.filter((n) => !recorded.includes(n));
    const extra = recorded.filter((n) => !declared.includes(n));

    expect(
      { missing, extra },
      'run `npm run licenses:generate` from the repo root and commit the result'
    ).toEqual({ missing: [], extra: [] });
  });

  it('keeps its counts in step with its lists', () => {
    expect(manifest.counts.client).toBe(manifest.client.length);
    expect(manifest.counts.server).toBe(manifest.server.length);
    expect(manifest.counts.total).toBe(manifest.client.length + manifest.server.length);
  });

  // webr declares "SEE LICENSE IN LICENCE.md", which attributes nothing. It
  // ships a WebAssembly build of R and its toolchain under GPL, which is worth
  // stating plainly on the attribution page of a proprietary-licensed product.
  it('resolves licences that would otherwise print a placeholder', () => {
    for (const dep of [...manifest.client, ...manifest.server]) {
      expect(dep.license, `${dep.name} has an unresolved licence`).not.toMatch(/SEE LICENSE IN/i);
      expect(dep.license.trim().length).toBeGreaterThan(0);
    }
  });
});

describe('version reporting', () => {
  it('matches package.json and is not the old hardcoded fallback', () => {
    const pkgVersion = readJson('server/package.json').version;
    expect(BUILD_INFO.version).toBe(pkgVersion);
    expect(BUILD_INFO.version).not.toBe('unknown');
  });

  it('is identical across the three packages', () => {
    const versions = ['package.json', 'client/package.json', 'server/package.json'].map(
      (p) => readJson(p).version
    );
    expect(new Set(versions).size, `versions disagree: ${versions.join(', ')}`).toBe(1);
  });

  // Two sources feed the stamp, so three shapes are legitimate:
  //   - build-info.json present  -> sha AND builtAt (the normal built artifact)
  //   - no stamp, .git readable  -> sha, but builtAt null (a source checkout,
  //     or a deploy whose rebuild called `npx tsc` and skipped the prebuild)
  //   - neither                  -> both null (a tarball with no .git)
  // What must never happen is a builtAt without a commit: anything claiming to
  // know when it was built must be able to say what it built.
  it('reports a coherent build stamp', () => {
    if (BUILD_INFO.gitSha !== null) {
      expect(BUILD_INFO.gitSha).toMatch(/^[0-9a-f]{7,40}$/);
    }
    if (BUILD_INFO.builtAt !== null) {
      expect(BUILD_INFO.gitSha, 'builtAt without a commit is not a usable stamp').not.toBeNull();
      expect(Number.isNaN(Date.parse(BUILD_INFO.builtAt))).toBe(false);
    }
  });

  // The whole point of the stamp is that a deployment can identify itself.
  // In a git checkout that must hold whether or not the prebuild ever ran.
  it('can identify itself from .git alone when no stamp was written', () => {
    expect(
      BUILD_INFO.gitSha,
      'no commit available from build-info.json or .git — /api/health cannot say what it is running'
    ).not.toBeNull();
  });
});
