/**
 * Test fixture: the smallest package that exercises every collection and
 * every kind of cross-reference. Shared by the schema, import and route tests.
 */
import type { CoursePackage } from './coursePackage.schema.js';

export const FIXTURE_FILE_URL = '/uploads/11111111-1111-1111-1111-111111111111-notes.pdf';
export const FIXTURE_FILE_SHA = 'a'.repeat(64);

export const minimalPackage = (): CoursePackage => ({
  course: {
    title: 'Learning Analytics 101',
    slug: 'learning-analytics-101-abc123',
    description: 'Intro',
    thumbnail: null,
    difficulty: 'beginner',
    isPublic: true,
    collaborativeModuleName: null,
    collaborativeModuleEnabled: true,
    emotionalPulseEnabled: true,
    tutorsEnabled: true,
    tutorRoutingMode: 'all',
    defaultTutorKey: 't1',
    curriculumViewMode: 'mini-cards',
    openLinkLecturesDirectly: true,
    enabledLabs: 'tna,sna',
    startTime: null,
  },
  categories: ['Analytics'],
  modules: [
    {
      key: 'm1',
      title: 'Week 1',
      description: null,
      label: null,
      orderIndex: 0,
      isPublished: true,
      availableFrom: '2026-09-01T00:00:00.000Z',
      availableUntil: null,
      interactiveLabs: null,
      lectures: [
        {
          key: 'le1',
          title: 'Welcome',
          description: null,
          content: null,
          contentType: 'text',
          videoUrl: null,
          duration: null,
          orderIndex: 0,
          isPublished: true,
          isFree: false,
          availableFrom: null,
          availableUntil: null,
          sections: [
            {
              title: 'Reading',
              type: 'text',
              content: `<p>Read this</p><lecture-file data-url="${FIXTURE_FILE_URL}" data-name="notes.pdf"></lecture-file>`,
              fileName: null,
              fileUrl: null,
              fileType: null,
              fileSize: null,
              order: 0,
              chatbotTitle: null,
              chatbotIntro: null,
              chatbotImageUrl: null,
              chatbotSystemPrompt: null,
              chatbotWelcome: null,
              assignmentKey: null,
              showDeadline: true,
              showPoints: true,
            },
            {
              title: 'Hand-in',
              type: 'assignment',
              content: null,
              fileName: null,
              fileUrl: null,
              fileType: null,
              fileSize: null,
              order: 1,
              chatbotTitle: null,
              chatbotIntro: null,
              chatbotImageUrl: null,
              chatbotSystemPrompt: null,
              chatbotWelcome: null,
              assignmentKey: 'a1',
              showDeadline: true,
              showPoints: false,
            },
          ],
          attachments: [{ fileName: 'notes.pdf', fileUrl: FIXTURE_FILE_URL, fileType: 'application/pdf', fileSize: 3 }],
        },
      ],
      codeLabs: [
        {
          title: 'R warm-up',
          description: null,
          orderIndex: 0,
          isPublished: false,
          availableFrom: null,
          availableUntil: null,
          aiChatbotName: 'ghost-helper',
          blocks: [{ title: 'Cell 1', instructions: null, starterCode: 'x <- 1', orderIndex: 0, locked: false, cellType: 'code' }],
        },
      ],
      moduleSurveys: [{ surveyKey: 's1', orderIndex: 0 }],
      children: [],
    },
  ],
  assignments: [
    {
      key: 'a1',
      moduleKey: 'm1',
      lectureKey: 'le1',
      title: 'Essay',
      description: null,
      instructions: 'Write',
      submissionType: 'text',
      maxFileSize: null,
      allowedFileTypes: null,
      dueDate: '2026-10-01T00:00:00.000Z',
      gracePeriodDeadline: null,
      availableFrom: null,
      availableUntil: null,
      points: 100,
      weight: 1,
      isPublished: false,
      aiAssisted: false,
      aiPrompt: null,
      agentRequirements: null,
      reflectionRequirement: null,
      postSurveyKey: 's1',
      postSurveyRequired: false,
      orderIndex: 0,
      attachments: [],
    },
  ],
  quizzes: [
    {
      key: 'q1',
      moduleKey: 'm1',
      title: 'Check',
      description: null,
      instructions: null,
      timeLimit: null,
      maxAttempts: 1,
      passingScore: 70,
      shuffleQuestions: false,
      shuffleOptions: false,
      showResults: 'after_submit',
      isPublished: false,
      dueDate: null,
      availableFrom: null,
      availableUntil: null,
      orderIndex: 0,
      questions: [
        {
          questionType: 'multiple_choice',
          questionText: '2+2?',
          options: '["3","4"]',
          correctAnswer: '4',
          explanation: null,
          points: 1,
          shuffleOptions: false,
          orderIndex: 0,
        },
      ],
    },
  ],
  surveys: [
    {
      key: 's1',
      title: 'Exit survey',
      description: null,
      isPublished: true,
      isAnonymous: false,
      questions: [{ questionText: 'Useful?', questionType: 'likert', options: null, isRequired: true, orderIndex: 0 }],
    },
  ],
  customLabs: [
    {
      key: 'l1',
      name: 'TNA lab',
      description: null,
      labType: 'r',
      config: '{}',
      aiChatbotName: null,
      cells: [{ title: 'Intro', description: null, content: null, code: '1+1', orderIndex: 0, locked: false, cellType: 'code' }],
    },
  ],
  labAssignments: [{ labKey: 'l1', moduleKey: 'm1', assignmentKey: null, orderIndex: 0, isPublished: true }],
  forums: [
    {
      moduleKey: 'm1',
      title: 'Introduce yourself',
      content: 'Say hi',
      description: null,
      isPublished: true,
      availableFrom: null,
      availableUntil: null,
      allowAnonymous: false,
      orderIndex: 0,
      isPinned: true,
      isLocked: false,
    },
  ],
  tutors: [
    {
      key: 't1',
      chatbot: {
        name: 'stats-tutor',
        displayName: 'Stats Tutor',
        description: null,
        systemPrompt: 'You teach statistics.',
        category: 'tutor',
        welcomeMessage: null,
        avatarUrl: null,
        personality: 'friendly',
        personalityPrompt: null,
        temperature: 0.7,
        suggestedQuestions: null,
        dosRules: null,
        dontsRules: null,
        responseStyle: 'balanced',
        maxTokens: 1000,
        modelPreference: null,
        knowledgeContext: null,
      },
      customName: null,
      customDescription: null,
      customSystemPrompt: null,
      customWelcomeMessage: null,
      customPersonality: null,
      customTemperature: null,
      isActive: true,
      displayOrder: 0,
    },
  ],
  rubrics: [
    {
      title: 'Essay rubric',
      description: null,
      isTemplate: false,
      criteria: [{ name: 'Clarity', description: null, maxPoints: 5, orderIndex: 0, levels: '[]' }],
    },
  ],
  files: [{ url: FIXTURE_FILE_URL, sha256: FIXTURE_FILE_SHA, size: 3 }],
});
