#!/bin/bash
# Generate prisma/local/schema.prisma (SQLite) from prisma/prod/schema.prisma (PostgreSQL).
# Run once after cloning, or after prisma/prod/schema.prisma changes.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PRISMA_DIR="$SCRIPT_DIR/../prisma"

mkdir -p "$PRISMA_DIR/local/migrations"

# Generate local SQLite schema from prod PostgreSQL schema
sed 's/provider = "postgresql"/provider = "sqlite"/' \
  "$PRISMA_DIR/prod/schema.prisma" > "$PRISMA_DIR/local/schema.prisma"

# Ensure local migration lock exists
cat > "$PRISMA_DIR/local/migrations/migration_lock.toml" << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "sqlite"
EOF

echo "Local SQLite schema generated: prisma/local/schema.prisma"
echo "Run 'npm run db:push' to sync your local database."
